language: ruby
rvm:
#  - 1.9.3
  - 2.0.0
  - ruby-head
  - jruby-head
  - rbx-19mode
  - jruby-19mode
matrix:
  allow_failures:
    - rvm: rbx-19mode
    - rvm: jruby-19mode
    - rvm: jruby-head
    - rvm: ruby-head
env:
#  - DB=sqlite
  - DB=mysql
  - DB=postgresql
before_install:
  - gem install bundler
bundler_args: "--without development"
before_script:
#  - [ "$DB" = 'postgresql' ] && psql -c 'create database zagirov.name_test;' -U postgres;
#  - [ "$DB" = 'mysql' ] && mysql -uroot -e 'create database `zagirov.name_test`'
#  - [ "$DB" = 'mysql' ] && mysql -uroot -e 'GRANT ALL ON `zagirov.name_test`.* TO "zagirov.name"@"localhost" IDENTIFIED BY "zagirov.name"; FLUSH PRIVILEGES;'
  - psql -c 'create database "zagirov_name_test";' -U postgres;
  - mysql -uroot -e 'create database `zagirov_name_test`'
  - mysql -uroot -e 'GRANT ALL ON `zagirov_name_test`.* TO "test"@"localhost" IDENTIFIED BY "test"; FLUSH PRIVILEGES;'
  - RAILS_ENV=test bundle exec rake --trace db:migrate test
  - cp config/application.yml.example config/application.yml

script: "bundle exec rspec spec/"
notifications:
  email:
    - rustam@zagirov.name
