language: ruby
rvm:
  - 1.9.3
  - 2.0.0
  - rbx-19mode
#  - jruby-19mode
env:
#  - DB=sqlite
  - DB=mysql
  - DB=postgresql
before_install:
  - gem install bundler
bundler_args: "--without development"
before_script:
  - sh -c "if [ '$DB' = 'postgresql' ]; then psql -c "create database zagirov.name_test;" -U postgres; fi"
  - sh -c "if [ '$DB' = 'mysql' ]; then mysql -uroot -e 'create database `zagirov.name_test`'; fi"
  - sh -c "if [ '$DB' = 'mysql' ]; then mysql -uroot -e 'GRANT ALL ON `zagirov.name_test`.* TO `zagirov.name`@`localhost` IDENTIFIED BY \'zagirov.name\'; FLUSH PRIVILEGES;'; fi"
  - RAILS_ENV=test bundle exec rake --trace db:migrate test


script: "bundle exec rspec spec/"
notifications:
  email:
    - rustam@zagirov.name
