language: ruby
rvm:
  - 1.9.3
  - 2.0.0
env:
#  - DB=sqlite
  - DB=mysql
#  - DB=postgresql
bundler_args: "--without development"
script: "rspec spec/"
before_script:
  - mysql -uroot -e 'create database `zagirov.name_test`'
  - mysql -uroot -e 'GRANT ALL ON `zagirov.name_test`.* TO "zagirov.name"@"localhost" IDENTIFIED BY "zagirov.name"; FLUSH PRIVILEGES;'
#  - bundle
  - RAILS_ENV=test bundle exec rake --trace db:migrate test
before_install:
  - gem install bundler

notifications:
  email:
    - rustam@zagirov.name